### ISSUE TITLE
npm run build or yarn run build is Failing - cross-env is not recognized

### ISSUE THREAD

**Issue by adithyaakrishna** [flatlogic/light-blue-react-template#10]
While running, npm run build, I'm getting this error

![image](https://user-images.githubusercontent.com/23498248/93814541-48701e00-fc72-11ea-8031-04fbf3fa5749.png)

and while using yarn build also, I got the same error. I'm kinda new to the cross-env thing. Do lmk how can i resolve this and how can get a production build of the site.

![image](https://user-images.githubusercontent.com/23498248/93815134-22974900-fc73-11ea-8b0d-c0e1c4f38cfd.png)

I wanted to build and deploy this app in netlify also, but still the same error there also.

**Comment by adithyaakrishna** [comment]
@Blari @okendoken @stepnov Sorry for the mention, but my whole project was done on this and we aren't able to build it. if you don't mind, pls do let me know what can I do here?

**Comment by dushyanthaKa** [comment]
Install cross env using 
yarn add cross-env
or 
npm install cross-env --save-dev to resolve this error
