### ISSUE TITLE
Template responsive is not working

### ISSUE THREAD

**Issue by shuklabhi** [flatlogic/light-blue-react-template#26]
Hello, 
In description found, This template is responsive. 
But when I tried on my mobile, this template is not responsive.  
![Mobile preview](https://user-images.githubusercontent.com/6838375/120651810-c987e200-c49c-11eb-8ec0-6e0636ea4dde.jpeg)

**Comment by erik0002** [comment]
Good day, @shuklabh. Thank you for your comment. We checked everything carefully and fixed the problem. The problem has been fixed for now. We apologize for the inconvenience caused to you. Have a nice day!)
