### ISSUE TITLE
Wile running npm install there are some errors

### ISSUE THREAD

**Issue by thedevilx** [flatlogic/light-blue-react-template#5]
![Issue](https://user-images.githubusercontent.com/23498248/87854795-e9202580-c931-11ea-80e8-0590d7058e8f.PNG)
[2020-07-18T14_32_53_971Z-debug.log](https://github.com/flatlogic/light-blue-react-template/files/4941820/2020-07-18T14_32_53_971Z-debug.log)

Do let me know what I can do to fix this?
I'm just getting started with React :)

**Comment by thedevilx** [comment]
I fixed it, lol

**Comment by netin17** [comment]
I am still getting this error

**Comment by thedevilx** [comment]
Try Yarn Install

Install yarn package manager and run yarn install
It should work then
