### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by neo4u** [flatlogic/light-blue-react-template#6]
Hi Team,

`npm install` doesn't work.

`yarn install` does work on the other hand.

I'm trying to understand why.

**Comment by opemipoVRB** [comment]
Just remove the     "bootstrap_calendar": "https://github.com/xero/bootstrap_calendar.git#1.0.1", in package.json Still looking for an alternative.

**Comment by guardofparadise** [comment]
We removed "bootstrap_calendar": "https://github.com/xero/bootstrap_calendar.git#1.0.1", from package.json
