### ISSUE TITLE
npm run build is not working

### ISSUE THREAD

**Issue by musafir-V** [flatlogic/light-blue-react-template#7]
npm run build shows error with script/ build.js.

**Comment by andr1312e** [comment]
in appsettings.json edit 
`     "bootstrap_calendar": ......`
to
`    "bootstrap-calendar": "0.2.4",`

use node 8

**Comment by andr1312e** [comment]
![image](https://user-images.githubusercontent.com/22058642/92414394-bab60e00-f15c-11ea-9c75-ffe8edefac1b.png)
Works fine
My package.json file

**Comment by guardofparadise** [comment]
We removed "bootstrap_calendar": "https://github.com/xero/bootstrap_calendar.git#1.0.1", from package.json
Consider using yarn if you face errors. 
Best regards
